config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'menus#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :orders
  resources :items
  resources :menus
  resources :users
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user

  has_many   :order_meals, inverse_of: :order,    dependent: :destroy
  has_many   :meals,       through: :order_meals, dependent: :nullify
  has_many   :items,       through: :meals,       dependent: :nullify

  accepts_nested_attributes_for :order_meals,
                                reject_if:     :all_blank,
                                allow_destroy: true

  validate :full?

  def full?
    errors.add(:meals) unless (Item.kinds.keys - ordered_kinds).blank?
  end

  def ordered_kinds
    OrderMealDecorator.decorate_collection(order_meals).map(&:meal_kind).uniq
  end
end

app/controllers/api/v1/orders_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class OrdersController < Api::V1::ApplicationController
      decorates_assigned :order

      def index
        @orders = Order.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)

        render json: Api::V1::OrderSerializer.new(@orders, include: %i[user meals items])
      end
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :check_policy

  decorates_assigned :order

  def index
    @facade = Orders::IndexFacade.new(params)
  end

  def new
    @facade = Orders::NewFacade.new(params)
  end

  def create
    @order = Orders::Create.call(order_params: order_params)

    return redirect_with_errors unless @order.valid?

    render :show
  end

  def show
    @order = Order.find_by(id: params[:id])
  end

  private

  def redirect_with_errors
    redirect_back(fallback_location: new_order_path, alert: t('validations.order.invalid'))
  end

  def check_policy
    authorize(@order || Order)
  end

  def order_params
    params
      .require(:order)
      .permit(:user_id,
              order_meals_attributes: %i[id _destroy meal_id order_id])
  end
end

app/views/orders/_daily_orders.html.haml
= form_tag orders_path, method: :get do
  .form-group.mb-3.mt-3
    .input-group
      %input#created_at.form-control.inline-block{ "data-provide": "datepicker", name: "created_at", type: "text" }
      .input-group-append
        %button.btn.btn-primary.inline-block{ "data-disable-with": "Searching", name: "commit", type: "submit" }= t('.search')

app/views/orders/_form.html.haml
= simple_form_for facade.order do |f|
  %h3= t('activerecord.models.order.one')
  = f.hidden_field :user_id, value: current_user.id
  #meals

    = f.simple_fields_for :order_meals, facade.order_meals do |order_meal|
      .nested-fields.well.well-compact
        .form-inline.mt-3
          = order_meal.input :meal_id, as: :select,
            collection: facade.first_lunches, label_method: :meal_info, value_method: :id, label: t('activerecord.attributes.item.kinds.first_lunch.one'),
            class: 'form-control', label_html: { class: 'mr-3' }

    = f.simple_fields_for :order_meals, facade.order_meals do |order_meal|
      .nested-fields.well.well-compact
        .form-inline.mt-3
          = order_meal.input :meal_id, as: :select,
            collection: facade.second_lunches, label_method: :meal_info, value_method: :id, label: t('activerecord.attributes.item.kinds.second_lunch.one'),
            class: 'form-control', label_html: { class: 'mr-3' }

    = f.simple_fields_for :order_meals, facade.order_meals do |order_meal|
      .nested-fields.well.well-compact
        .form-inline.mt-3
          = order_meal.input :meal_id, as: :select,
            collection: facade.drinks, label_method: :meal_info, value_method: :id, label: t('activerecord.attributes.item.kinds.drink.one'),
            class: 'form-control', label_html: { class: 'mr-3' }

    = f.button :submit, class: 'btn btn-primary mt-3'

app/views/orders/index.html.haml
%h1.text-center
  = t('.title')

= render 'daily_orders', facade: @facade

%table.table.table-striped
  %thead
    %tr
      %th= t('activerecord.attributes.order.orderer')
      %th= t('activerecord.attributes.order.ordered')
      %th= t('activerecord.attributes.order.price')
      %th= t('actions.title')
  %tbody
    - @facade.orders.each do |order|
      %tr
        %td= order.username
        %td= order.ordered_time
        %td= order.order_price
        %td= link_to t('buttons.show'), order
    %tr
      %td
      %th= t('activerecord.attributes.order.total')
      %th= @facade.orders_cost
      %td

app/views/orders/new.html.haml
%h1.text-center
  = t('.title')

= render 'form', facade: @facade

app/views/orders/show.html.haml
%h1.text-center
  = t('.title', time_ordered: order.ordered_time)

%p
  %b= t('activerecord.attributes.order.orderer')
  = order.username

%table.table.table-striped
  %thead
    %tr
      %th= t('activerecord.attributes.item.name')
      %th= t('activerecord.attributes.item.kind')
      %th= t('activerecord.attributes.item.price')
  %tbody
    - order.order_meals.each do |order_meal|
      %tr
        %td= order_meal.meal_name
        %td= order_meal.meal_kind
        %td= order_meal.meal_price
    %tr
      %td
      %th= t('activerecord.attributes.order.total')
      %td= order.order_price

.text-center
  %a.btn.btn-secondary{ href: menus_path }= t('buttons.back')