config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'menus#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :orders
  resources :items
  resources :menus
  resources :users
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  has_many :meals
  has_many :menus, through: :meals

  validates :name, :price, :kind, presence: true

  validates :name,  uniqueness:   true
  validates :name,  length:       { in: User::NAME_LENGTH }
  validates :price, numericality: { greater_than: 0 }

  enum kind: {
    first_lunch:  FIRST_LUNCH  = 'first',
    second_lunch: SECOND_LUNCH = 'second',
    drink:        DRINK        = 'drink'
  }
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, except: %i[index new create]
  before_action :check_policy

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Items::Create.call(item_params: item_params)

    return respond_with(@item) unless @item.valid?

    render :show
  end

  def update
    respond_with update_item, location: item_path(@item)
  end

  private

  def check_policy
    authorize(@item || Item)
  end

  def update_item
    Items::Update.call(
      item:        @item,
      item_params: item_params
    )
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params
      .require(:item)
      .permit(:name, :price, :kind)
  end
end

app/views/items/_form.html.haml
= simple_form_for item do |f|
  = f.input  :name
  = f.input  :kind, as: :select, collection: Item.kinds
  = f.input  :price
  = f.button :submit

app/views/items/edit.html.haml
%h1.text-center
  = t('.title', item: @item.name)

= render 'form', item: @item

.text-center
  %a.btn.btn-secondary{ href: item_path(@item) }= t('buttons.back')

app/views/items/index.html.haml
%h1.text-center
  = t('.title')

%table.table.table-striped
  %thead
    %tr
      %th= t('activerecord.attributes.item.name')
      %th= t('activerecord.attributes.item.kind')
      %th= t('activerecord.attributes.item.price')
      %th= t('actions.title')
  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.kind
        %td= item.price
        %td
          = link_to t('buttons.show'), item
          = link_to t('buttons.edit'), edit_item_path(item)

.text-center
  %a.btn.btn-primary{ href:  new_item_path }= t('.buttons.new')

app/views/items/new.html.haml
%h1.text-center
  = t('.title')

= render 'form', item: @item

.text-center
  %a.btn.btn-secondary{ href: items_path }= t('buttons.back')

app/views/items/show.html.haml
%h1.text-center
  = t('.title', item: @item.name)

%table.table.table-striped
  %thead
    %th= t('activerecord.attributes.item.name')
    %th= t('activerecord.attributes.item.kind')
    %th= t('activerecord.attributes.item.price')
  %tbody
    %td= @item.name
    %td= @item.kind
    %td= @item.price

.text-center
  %a.btn.btn-primary{ href:  edit_item_path(@item) }= t('buttons.edit')
  %a.btn.btn-secondary{ href: items_path }= t('buttons.back')